name: Release Service Portal

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  KUBECONFIG: .kube/config
  KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    environment: release 
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: generate-image-tag
        name: Generate Image Tag
        env:
          # The branch or tag name that triggered the workflow
          ref_name: "${{ github.ref_name }}"
          # The source branch of a pull request (only set in PRs)
          head_ref: "${{ github.head_ref }}"
        # Replace slashes in branch names, determine final image name, set output variable imageTag
        run: |
          head_ref="${head_ref/\//-}"
          tag="${head_ref:-${ref_name}}"
          tag="${tag#v}"
          echo "imageTag=tag" >> "$GITHUB_OUTPUT"

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          # use a) human-readable and b) immutable tag
          tags: |
            ghcr.io/${{ github.repository }}/backend:${{ steps.generate-image-tag.outputs.imageTag }}
            ghcr.io/${{ github.repository }}/backend:${{ github.event.pull_request.head.sha || github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: |
            npm_token=${{ secrets.NPM_TOKEN }}
      
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
  deploy_main:
    environment: release-k8s
    needs: build-and-push-image
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Kubernetes config
        run: |
          mkdir -p .kube
          echo "${{ env.KUBECONFIG_FILE }}" > $KUBECONFIG

      - name: Create K8s secret for SMTP_API_KEY
        run: |
          kubectl create secret generic ts4nfdi-service-portal-smtp-api-key \
            --from-literal=SMTP_API_KEY=${{ secrets.SMTP_API_KEY }} \
            --namespace='ts4nfdi' \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Create K8s secret for SMTP_USERNAME
        run: |
          kubectl create secret generic ts4nfdi-service-portal-smtp-username \
            --from-literal=SMTP_USERNAME=${{ secrets.SMTP_USERNAME }} \
            --namespace='ts4nfdi' \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Create K8s secret for SMTP_PASSWORD
        run: |
          kubectl create secret generic ts4nfdi-service-portal-smtp-password \
            --from-literal=SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }} \
            --namespace='ts4nfdi' \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Create K8s secret for CAPTCHA_VALIDATION_URL
        run: |
          kubectl create secret generic ts4nfdi-service-portal-captcha-validation-url \
            --from-literal=CAPTCHA_VALIDATION_URL=${{ secrets.CAPTCHA_VALIDATION_URL }} \
            --namespace='ts4nfdi' \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Create K8s secret for CAPTCHA_API_KEY
        run: |
          kubectl create secret generic ts4nfdi-service-portal-captcha-api-key \
            --from-literal=CAPTCHA_API_KEY=${{ secrets.CAPTCHA_API_KEY }} \
            --namespace='ts4nfdi' \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Create K8s secret for AUTH_SECRET
        run: |
          kubectl create secret generic ts4nfdi-service-portal-auth-secret \
            --from-literal=AUTH_SECRET=${{ secrets.AUTH_SECRET }} \
            --namespace='ts4nfdi' \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Create K8s secret for CONTACT_RECV_EMAIL
        run: |
          kubectl create secret generic ts4nfdi-service-portal-contact-recv-email \
            --from-literal=CONTACT_RECV_EMAIL=${{ secrets.CONTACT_RECV_EMAIL }} \
            --namespace='ts4nfdi' \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Create K8s secret for SMTP_HOST_NAME
        run: |
          kubectl create secret generic ts4nfdi-service-portal-smtp-host-name \
            --from-literal=SMTP_HOST_NAME=${{ vars.SMTP_HOST_NAME }} \
            --namespace='ts4nfdi' \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Create K8s secret for SERVICE_EMAIL
        run: |
          kubectl create secret generic ts4nfdi-service-portal-smtp-service-email \
            --from-literal=SERVICE_EMAIL=${{ vars.SERVICE_EMAIL }} \
            --namespace='ts4nfdi' \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Create K8s secret for GATEWAY_BASE_URL
        run: |
          kubectl create secret generic ts4nfdi-service-portal-gateway-base-url \
            --from-literal=GATEWAY_BASE_URL=${{ vars.GATEWAY_BASE_URL }} \
            --namespace='ts4nfdi' \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to Kubernetes
        uses: stefanprodan/kube-tools@v1
        with:
          helmv3: 3.12.0
          command: |
            kubectl get nodes
            helmv3 repo add service-portal-deployment https://ts4nfdi.github.io/service-portal-deployment/
            helmv3 repo update
            helmv3 upgrade ts4nfdi-service-portal \
              --install \
              --namespace='ts4nfdi' \
              --set-json='ingress.dns="ts4nfdi-service-portal.qa.km.k8s.zbmed.de"'  \
              --set-json='images.ui="ghcr.io/${{ github.repository }}:${{ github.event.pull_request.head.sha || github.sha }}"' \
              --set-json='ingress.path="/"' \
              service-portal-deployment/service-portal-ui
